# Date : starting date for the data set of tweets.
# Example : YYYY-MM-DD
date : 2018-10-08

# Duration of the data set
days : 30

# Number of tweets
message_number : 200000

# Number of user
number_user : 1000

# Name Index
index_name: 'messages'

# Do you want to index it or have it on a file
index: false

# Override the index
override: false

# Add users
names :
  - !!python/tuple ['Shay','Banon']

distributions:
  # Configure the distribution of the number of subjects to allocate to a specific user
  favorite_subjects_per_user_distribution:
    # Accepted values for type are: normal | exponential
    # For a normal distribution the parameters that need to be defined are the following: mean, sd, lower_bound, upper_bound
    # For a exponential distribution the parameters that need to be defined are the following: scale, lower_bound, upper_bound
    type: "exponential"
    params:
      mean: 4.7
      sd: 'e'
      lower_bound: 2
      upper_bound: 'e'

  subjects_distribution:
    # Accepted values for type are: normal | exponential
    type: "exponential"
    params:
      scale: 2
      lower_bound: 'a'
      upper_bound: 10

  age_distribution:
    params:
      mean: 37
      sd: 6
      lower_bound: 20
      upper_bound: 60

message_generation:
  granularity: 'h'
  path: 'datasets/message_distribution.txt'
  noise: 0.25