# Date : starting date for the data set of tweets.
# Example : YYYY-MM-DD
date : 2018-10-08

# Duration of the data set
days : 30

# Number of tweets
tweet_number : 200000

# Number of user
number_user : 1000

# Add users
names :
  - !!python/tuple ['Shay','Banon']

distributions:
  # Configure the distribution of the number of subjects to allocate to a specific user
  favorite_subjects_per_user_distribution:
    # Accepted values for type are: normal | exponential
    # For a normal distribution the parameters that need to be defined are the following: mean, sd, lower_bound, upper_bound
    # For a exponential distribution the parameters that need to be defined are the following: scale, lower_bound, upper_bound
    type: "normal"
    params:
      mean: 4.8
      sd: 1.2
      lower_bound: 1
      upper_bound: 7

  subjects_distribution:
    # Accepted values for type are: normal | exponential
    type: "exponential"
    params:
      scale: 2
      lower_bound: 1
      upper_bound: 10

  age_distribution:
    params:
      mean: 37
      sd: 6
      lower_bound: 20
      upper_bound: 60

message_generation:
  granuraty: h
  path: ''
  delta: ''